version: '3.8'

services:
 postgres: #custom name
  image: postgres
  ports:
   - '1234:5432'
  environment:
   POSTGRES_USER: postgres
   POSTGRES_DB: mydb
   POSTGRES_PASSWORD: password
 redis: #custom name
  image: redis
  ports:
   - '6379:6379'
 apache: #custom name
  image: httpd
  ports:
   - '80:80'
